### ISSUE TITLE
Will there be a typings file?

### ISSUE THREAD

**Issue by Cyber1000** [beefsack/node-hound#12]
Hi,

Liking this project, does work very well so far.
As I'm using mainly typescript, it would be nice if there were any typings, but I couldn't find one with typings install hound.

Are you planning to offer a typescript-definition-file or is there some (inofficial?) d.ts?

Thanks!

**Comment by beefsack** [comment]
Hi @Cyber1000, unfortunately I don't have a plan to make a typescript definition, but would be more than happy to look at any contributions which might look to add them.
